---
apiVersion: v1
kind: Secret
metadata:
  name: ama2-photo-generator-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/WindTurbineInc/ama2-photo-generator-gitops
